# Generated by Django 4.2.4 on 2023-10-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTarjeta', models.IntegerField()),
                ('codigoVerificacion', models.IntegerField()),
                ('fechaVencimiento', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idBanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.proveedores')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cliente')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.banco')),
            ],
        ),
    ]
