# Generated by Django 4.2.4 on 2023-10-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_campaignreceiver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CampaignReceiver',
            new_name='Tarjeta',
        ),
    ]
